Repository goreleaser/fileglob, pull requests merged in 2020-11, with the labels that each got.

#1 feat: options
  glob.go
  glob_test.go
Labels: size/M

#3 test: add more tests
  glob_test.go
Labels: automerge, enhancement, size/S

#5 refactor: separator et al
  doc.go
  glob.go
  glob_test.go
  prefix.go
  prefix_test.go
Labels: automerge, enhancement, size/M

#7 feat: Add ContainsMatchers and ValidPattern.
  prefix.go
  prefix_test.go
Labels: size/L

#6 fix: handle file not found
  glob.go
  glob_test.go
  prefix.go
Labels: automerge, enhancement, size/M

#9 test: Add error type check in test.
  glob_test.go
Labels: size/XS

#8 test: added failing tests
  glob_test.go
Labels: size/S
